### ISSUE TITLE
Readability improvement - Findbar

### ISSUE THREAD

**Issue by mpred04** [nt1m/weatherlicious#3]
On most of the dark themes I run into the following when opening findbar:

![2018-08-07 18_36_52-window](https://user-images.githubusercontent.com/7307115/43786554-8e338b76-9a71-11e8-8b8f-67239af306c3.jpg)

If we get the text we search becoming white, can the findbar (or search field) background please be a different color?

**Comment by nt1m** [comment]
Good catch, I'll see how I can fix it.

**Comment by mpred04** [comment]
Seems like it's fixed?

![изображение](https://user-images.githubusercontent.com/7307115/58386732-9b00e200-800c-11e9-9ed9-56f9cbca0e14.png)

**Comment by nt1m** [comment]
It probably has been fixed upstream in Firefox. Thanks for checking again!
