### ISSUE TITLE
Suggestion - dark about pages possible?

### ISSUE THREAD

**Issue by mpred04** [nt1m/weatherlicious#5]
Based on [this thread on reddit](https://www.reddit.com/r/FirefoxCSS/comments/chfzqp/best_dark_interface_to_date_firefox_68_stable_no/), wanted to ask, is implementing some of the dark options (like for about pages) noted there would be possible (unfortunately, not certain myself)?

edit: thanks for looking into it!

**Comment by nt1m** [comment]
@mpred04 Following steps 2/3/4 (without 1) on that reddit post should work fine. I unfortunately can't do this automatically though.
